export const CARD_PAIRS: [string, string][] = [
  ["Knight", "Mini P.E.K.K.A"],
  ["Giant", "Royal Giant"],
  ["P.E.K.K.A", "Mega Knight"],
  ["Hog Rider", "Ram Rider"],
  ["Balloon", "Lava Hound"],
  ["Witch", "Night Witch"],
  ["Wizard", "Electro Wizard"],
  ["Ice Wizard", "Ice Golem"],
  ["Archers", "Firecracker"],
  ["Musketeer", "Dart Goblin"],
  ["Three Musketeers", "Royal Recruits"],
  ["Barbarians", "Elite Barbarians"],
  ["Skeleton Army", "Goblin Gang"],
  ["Minions", "Minion Horde"],
  ["Bats", "Skeletons"],
  ["Prince", "Dark Prince"],
  ["Golem", "Elixir Golem"],
  ["Miner", "Goblin Drill"],
  ["Sparky", "Inferno Dragon"],
  ["Baby Dragon", "Electro Dragon"],
  ["Bowler", "Executioner"],
  ["Valkyrie", "Lumberjack"],
  ["Bandit", "Golden Knight"],
  ["Archer Queen", "Magic Archer"],
  ["Skeleton King", "Giant Skeleton"],
  ["Monk", "Little Prince"],
  ["Phoenix", "Flying Machine"],
  ["Wall Breakers", "Skeleton Barrel"],
  ["Battle Ram", "Royal Hogs"],
  ["Cannon Cart", "Goblin Machine"],
  ["Fisherman", "Hunter"],
  ["Mother Witch", "Princess"],
  ["Zappies", "Rascals"],
  ["Fireball", "Rocket"],
  ["Arrows", "The Log"],
  ["Zap", "Giant Snowball"],
  ["Freeze", "Tornado"],
  ["Poison", "Earthquake"],
  ["Lightning", "Royal Delivery"],
  ["Goblin Barrel", "Graveyard"],
  ["Rage", "Clone"],
  ["Barbarian Barrel", "Void"],
  ["Cannon", "Tesla"],
  ["Inferno Tower", "Bomb Tower"],
  ["X-Bow", "Mortar"],
  ["Goblin Hut", "Barbarian Hut"],
  ["Furnace", "Tombstone"],
  ["Goblin Cage", "Elixir Collector"],
  ["Mega Minion", "Bomber"],
  ["Guards", "Goblins"],
  ["Heal Spirit", "Battle Healer"],
  ["Ice Spirit", "Electro Spirit"],
  ["Fire Spirit", "Skeleton Dragons"],
  ["Electro Giant", "Goblin Giant"],
  ["Spear Goblins", "Suspicious Bush"]
];
