// 60 Thematic Clash Royale Card Pairs
// Note: A few versatile cards (e.g. Lava Hound, Mini P.E.K.K.A, Ice Spirit, Giant, Rage)
// appear in up to two pairs to provide diverse role matches.
export const CARD_PAIRS: [string, string][] = [
  ["Skeleton Army", "Goblin Gang"],
  ["Minions", "Bats"],
  ["Fireball", "Rocket"],
  ["Arrows", "The Log"],
  ["Zap", "Giant Snowball"],
  ["Hog Rider", "Ram Rider"],
  ["Giant", "Royal Giant"],
  ["Golem", "Elixir Golem"],
  ["Wizard", "Electro Wizard"],
  ["Ice Wizard", "Ice Spirit"],
  ["Musketeer", "Archers"],
  ["Three Musketeers", "Elite Barbarians"],
  ["Barbarians", "Goblins"],
  ["Valkyrie", "Mini P.E.K.K.A"],
  ["P.E.K.K.A", "Mega Knight"],
  ["Prince", "Dark Prince"],
  ["Balloon", "Lava Hound"],
  ["Baby Dragon", "Inferno Dragon"],
  ["Witch", "Night Witch"],
  ["Bomber", "Firecracker"],
  ["Dart Goblin", "Spear Goblins"],
  ["Knight", "Valkyrie"],
  ["Tesla", "Inferno Tower"],
  ["Cannon", "Bomb Tower"],
  ["Tombstone", "Goblin Hut"],
  ["Furnace", "Barbarian Hut"],
  ["Elixir Collector", "Goblin Cage"],
  ["Poison", "Earthquake"],
  ["Lightning", "Rocket"],
  ["Freeze", "Tornado"],
  ["Rage", "Clone"],
  ["Mirror", "Heal Spirit"],
  ["Goblin Barrel", "Graveyard"],
  ["Miner", "Goblin Drill"],
  ["Princess", "Magic Archer"],
  ["Hunter", "Executioner"],
  ["Bandit", "Royal Ghost"],
  ["Electro Dragon", "Electro Giant"],
  ["Sparky", "Mega Knight"],
  ["Archer Queen", "Golden Knight"],
  ["Skeleton King", "Mighty Miner"],
  ["Little Prince", "Monk"],
  ["Phoenix", "Electro Spirit"],
  ["Goblin Machine", "Goblinstein"],
  ["Suspicious Bush", "Barbarian Barrel"],
  ["Battle Ram", "Battle Healer"],
  ["Cannon Cart", "Flying Machine"],
  ["Zappies", "Minion Horde"],
  ["Guards", "Skeletons"],
  ["Wall Breakers", "Skeleton Barrel"],
  ["Rascals", "Royal Recruits"],
  ["Royal Hogs", "Royal Delivery"],
  ["Fisherman", "Lumberjack"],
  ["Mother Witch", "Witch"],
  ["Goblin Curse", "Void"],
  ["Skeleton Dragons", "Flying Machine"],
  ["X-Bow", "Mortar"],
  ["Giant Skeleton", "Bowler"],
  ["Ice Golem", "Ice Spirit"],
  ["Goblin Giant", "Giant"]
];
