export const ERROR_MESSAGES: Record<string, string> = {
  BAD_REQUEST: 'Invalid request payload or parameters.',
  NAME_TAKEN: 'That display name is already taken in this party.',
  ROOM_NOT_FOUND: 'Party not found. Please check your party code.',
  ROOM_FULL: 'This party is full (maximum 30 players).',
  ROOM_EXPIRED: 'This party has expired due to inactivity.',
  NOT_LEADER: 'Only the party leader can perform this action.',
  NOT_A_PLAYER: 'You are not a member of this party.',
  WRONG_PHASE: 'Action not allowed during the current game phase.',
  ALREADY_SUBMITTED: 'You have already submitted your message for this round.',
  ALREADY_VOTED: 'You have already cast your vote for this match.',
  NOT_ENOUGH_PLAYERS: 'Need at least 3 active players to start.',
  SELF_VOTE: 'You cannot vote for yourself.',
  SPECTATOR_FORBIDDEN: 'Spectators cannot submit messages or vote.',
  ELIMINATED_FORBIDDEN: 'Eliminated players cannot submit messages or vote.',
  RATE_LIMITED: 'Too many requests. Please slow down.',
  CONFLICT_RETRY: 'System busy with simultaneous updates. Please try again.',
  INTERNAL: 'An unexpected internal error occurred.',
};

export const UI_STRINGS = {
  APP_TITLE: 'CARD IMPOSTER',
  APP_TAGLINE: 'A Clash Royale social-deduction word game',
  CREATE_PARTY: 'Create Party',
  JOIN_PARTY: 'Join Party',
  START_GAME: 'Start Game',
  PLAY_AGAIN: 'Play Again',
  END_PARTY: 'End Party',
  LEAVE_PARTY: 'Leave Party',
  COPY_LINK: 'Copy Party Link',
  LINK_COPIED: 'Copied!',
  YOUR_NAME: 'Your Display Name',
  PARTY_CODE: 'Party Code',
  NEED_MIN_PLAYERS: 'Need at least 3 players to start',
  SPECTATOR_BANNER: "You'll join the next match as an active player!",
  HOLD_TO_REVEAL: 'Hold to reveal your card',
  CREW_WINS: 'CREW WINS',
  IMPOSTER_WINS: 'IMPOSTER WINS',
  NOBODY_ELIMINATED: 'Nobody was eliminated due to a vote tie!',
  WAITING_FOR_LEADER: 'Waiting for leader to start the next match...',
};
